server:
  port: 8080

kitchen:
  minimize_decay: true
  topology:
    - name: "overflow"
      capacity: 20
      decay_rate: 2
      supported: 
        - hot
        - cold
        - frozen
    - name: "hot"
      capacity: 15
      decay_rate: 1
      supported: 
        - hot
    - name: "fridge"
      capacity: 15
      decay_rate: 1
      supported: 
        - cold
    - name: "freezer"
      capacity: 15
      decay_rate: 1
      supported: 
        - frozen